# Scan git repos (or files) for secrets using regex and entropy 🔑

name: gitLeaks

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          submodules: recursive
      - name: wget
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/ycjcl868/gitleaks/master/.gitleaks.toml
      - name: gitleaks-action
        uses: ./.github/actions/gitleaks-action
